version: '3.5'
services:
  chrome:
    image: selenium/node-chrome-debug:3.11.0-californium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
    ports:
      - "5900:5900"  
    networks:
      - protractortest
  hub:
    image: selenium/hub:3.11.0-californium
    ports:
      - "4444:4444"
    networks:
      - protractortest
  angular:
    image: node:6-alpine
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    command: ["npm", "start"]
    networks:
      - protractortest
networks:
  protractortest:
    name: protractortest